---
- name: install nopcommerce
  hosts: node1
  become: yes
  vars: 
    info_page_path: /home/ubuntu
  tasks:
    - name: copy url
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/{{ os_version }}/packages-microsoft-prod.deb
        dest: "{{ info_page_path }}"
      notify:
        - install the debian package
    - name: install dotnet
      ansible.builtin.apt: 
        name: "{{ dotnet_version}}"
        update_cache: yes
        state: present
    - name: install unzip
      ansible.builtin.apt: 
        name: unzip
        update_cache: yes
        state: present
    - name: Create a directory nopcommerce
      ansible.builtin.file:
        path: /usr/share/nopCommerce
        state: directory
    - name: Download foo.conf
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.3/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /usr/share/nopCommerce
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /usr/share/nopCommerce/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /usr/share/nopCommerce
        remote_src: yes
    - name: Create a directory bin 
      ansible.builtin.file:
        path: /usr/share/nopCommerce/bin
        state: directory
    - name: Create a directory logs
      ansible.builtin.file:
        path: /usr/share/nopCommerce/logs
        state: directory
    - name: Execute dotnet command
      command: /usr/bin/dotnet Nop.Web.dll --urls "http://0.0.0.0:5000"
      args:
        chdir: /usr/share/nopCommerce
  handlers:
    - name: install the debian package
      ansible.builtin.dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install