---
- name: install nopcommerce
  hosts: node1
  become: yes
  vars: 
    info_page_path: /home/ubuntu
  tasks:
    - name: copy url
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/{{ os_version }}/packages-microsoft-prod.deb
        dest: "{{ info_page_path }}"
    - name: install the debian package
      ansible.builtin.dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install
      notify:
        - stop install package
    - name: Remove packages-microsoft-prod.deb
      ansible.builtin.file:
        path: "{{ info_page_path }}"
        state: absent
    - name: install dotnet
      ansible.builtin.apt: 
        name: "{{ dotnet_version}}"
        update_cache: yes
        state: present
