apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deploy
  labels: 
    app: jenkins
spec: 
  minReadySeconds: 1
  replicas: 3
  selector: 
    matchLabels: 
      app: jenkins
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata: 
      name: jenkins
      labels:
        app: jenkins
        ver: "1.23"
    spec: 
      containers: 
        - name: jenkins
          image: jenkins/jenkins
          ports: 
            - containerPort: 80
