apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc
  labels: 
    app: nginx
spec: 
  selector: 
    name: nginx-pod
  minReadySeconds: 3
  replicas: 4
  template: 
    metadata: 
      labels: 
        name: nginx-pod
    spec: 
      containers: 
        - name: nginx-container
          image: nginx:1.23
          ports: 
            - containerPort: 80
