---
- name: metricbeat
  become: yes
  hosts: node1
  tasks: 
    - name: install transport
      apt: 
        name: apt-transport-https
        state: present
    - name: download metricbeat file
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: apt-key add -
    - name: copy the info.php page
      ansible.builtin.copy:
        content: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        dest: /etc/apt/sources.list.d/elastic-8.x.list
    - name: install metricbeat 
      apt:
        name: metricbeat
        state: present
        update_cache: true
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: metricbeat
        enabled: true
       