---
- name: metricbeat
  become: yes
  hosts: node1
  tasks: 
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: this playbook is designed for Ubntu only
      when: ansible_facts['os_family'] == 'Ubuntu'
    - name: install transport
      apt: 
        name: apt-transport-https
        state: present
    - name: download metricbeat file and add it to apt-keys
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    - name: copy repository information
      ansible.builtin.copy:
        content: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        dest: /etc/apt/sources.list.d/elastic-8.x.list
    - name: install metricbeat 
      apt:
        name: metricbeat
        state: present
        update_cache: true
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: metricbeat
        state: started