apiVersion: batch/v1
kind: Job
metadata: 
  name: period-job
spec: 
  template: 
    metadata: 
      name: one-job
    spec: 
      restartPolicy: OnFailure
      containers: 
        - name: alpine
          image: alpine
          ports: 
            - containerPort: 80
          commands: 
            - sleep
            - 3s 